server:
  port: 8090
  servlet:
    context-path: /card
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
          hibernate:
            format_sql: true

#  liquibase:
#    change-log: classpath:liquibase/changelog-master.yml

feign:
  local:
    client:
      auth:
        url: http://localhost:8091
        path: /auth

logging:
  level:
    az:
      unibank:
        msauth: DEBUG

management:
  info:
    java:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'shutdown, liquibase, env'